CREATE TABLE IF NOT EXISTS plantas(
    qrcode TEXT,
    familia TEXT,
    nome_cientifico TEXT,
    nome_popular TEXT,
    grupo_ecologico TEXT,
    origem TEXT,
    centro_origem TEXT,
    ocorrencia TEXT,
    bioma TEXT,
    floracao TEXT,
    frutificacao TEXT,
    sexo TEXT,
    s_polinizacao TEXT,
    tipo_fruto TEXT,
    s_dispersao TEXT,
    tipo_folha TEXT,
    filotaxia TEXT,
    descricao TEXT); 



INSERT INTO plantas (qrcode,
				     familia,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao) 
    VALUES ('QR-BordoJapones',
			'ACERACEA',
			'Acer palmatum Thunb.',
			'Bordo-japonês',
			'Secundária',
			'Exótica',
			'Japão, Coréia do Sul e China',
			'',
			'Floresta Temperada',
			'Abril',
			'Abril e Junho',
			'Polígamo-monóica',
			'Entomofilia',
			'Sâmara',
			'Anemocoria',
			'Folha Simples',
			'Oposta',
			'descricao');
