--drop table plantas2;

CREATE TABLE IF NOT EXISTS plantas2(
    qrcode TEXT,
	qrcode2 TEXT,
	qtde_imagem TEXT,
    familia TEXT,
	binomio TEXT,
	autores TEXT,
    nome_cientifico TEXT,
    nome_popular TEXT,
    grupo_ecologico TEXT,
    origem TEXT,
    centro_origem TEXT,
    ocorrencia TEXT,
    bioma TEXT,
    floracao TEXT,
    frutificacao TEXT,
    sexo TEXT,
    s_polinizacao TEXT,
    tipo_fruto TEXT,
    s_dispersao TEXT,
    tipo_folha TEXT,
    filotaxia TEXT,
    descricao TEXT,
	utilizacoes TEXT); 


--BORDO-JAPONES

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-BordoJapones',
			'QR-BordoJapones',
			'6',
			'ACERACEA',
			'Acer palmatum',
			'Thunb.',
			'Acer palmatum Thunb.',
			'Bordo-japonês',
			'-',
			'Exótica',
			'Japão, Coréia do Sul e China',
			'',
			'Floresta Temperada',
			'abril',
			'abril a junho',
			'Polígamo-monóica',
			'Entomofilia',
			'Sâmara',
			'Anemocoria',
			'Folha Simples',
			'Oposta',
			'descricao',
			'Por sua beleza excepcional, porte pequeno e raízes não invasivas, o bôrdo-japonês é uma árvore ideal para a arborização urbana, sendo apropriado para jardins residenciais e calçadas, inclusive sob a fiação. É uma planta muito visada e popular para a arte do bonsai.');

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-BordoVermelho',
			'QR-BordoVermelho',
			'6',
			'ACERACEA',
			'Acer rubrum',
			'L.',
			'Acer rubrum L.',
			'Bordo-vermelho',
			'-',
			'Exótica',
			'América do Norte e Canadá',
			'',
			'Floresta Temperada',
			'março a maio',
			'abril a junho',
			'Polígamo-dióica',
			'Entomofilia',
			'Sâmara',
			'Anemocoria',
			'Folha Simples',
			'Oposta',
			'descricao',
			'Arborização urbana e indústria alimentícia para a prodrução do xarope de bordo (Maple Syrup).');

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Liquidambar',
			'QR-Liquidambar',
			'4',
			'ALTINGIACEAE',
			'Liquidambar styraciflua',
			'L.',
			'Liquidambar styraciflua L.',
			'Liquidambar',
			'-',
			'Exótica',
			'América do Norte e Central',
			'',
			'Floresta Temperada',
			'março a maio',
			'setembro a novembro',
			'Monóica',
			'Anemofilia',
			'Cápsula',
			'Anemocoria',
			'Folha Simples',
			'Alterna',
			'descricao',
			'Arborização urbana. Produção de madeira de baixa densidade, podendo ser utilizada para diferentes finalidades, como movelaria, caixaria, paletes, compensados e polpa.');

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Aroeira-salsa',
			'QR-Aroeira-salsa',
			'4',
			'ANACARDIACEAE',
			'Schinus molle',
			'L.',
			'Schinus molle L.',
			'Aroeira-salsa',
			'Pioneira à secundária',
			'Nativa',
			'',			   	 
			'Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',					
			'Mata Atlântica, Pampa',
			'agosto a dezembro',
			'dezembro a fevereiro',
			'Monóica',
			'Entomofilia',
			'Drupa',
			'Zoocoria e Hidrocoria',
			'Folha composta',
			'Alterna',
			'descricao',
			'Arborização urbana, construção civil, marcenaria, mourões de cerca, lenha e carvão. A casca contém tanino, sendo usada em curtumes. Espécie indicada para a restauração de ecossistemas degradados.');		 



INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Pinheiro-do-Paraná',
			'QR-Pinheiro-do-Paraná',
			'4',
			'ARACAURIACEAE',
			'Araucaria angustifolia',
			'(Bertol.) Kuntze',
			'Araucaria angustifolia (Bertol.) Kuntze',
			'Pinheiro-do-Paraná',
			'Pioneira',
			'Nativa',
			'',		 
			'Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',				   	 			 
			'Mata Atlântica',
			'agosto a janeiro',
			'abril a junho',
			'Dióica',
			'Anemofilia',
			'As sementes estão reunidas no estróbilo feminino',
			'Zoocoria',
			'Folha simples',
			'Alterna',
			'descricao',
			'Indústria madeireira, alimentação humana e uso paisagístico. Espécie indicada para a restauração de ecossistemas degradados.');



INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Ipê-amarelo',
			'QR-Ipê-amarelo',
			'4',
			'BIGNONIACEAE ',
			'Handroanthus chrysotrichus',
			'(Mart. ex DC.) Mattos',
			'Handroanthus chrysotrichus (Mart. ex DC.) Mattos',
			'Ipê-amarelo ',
			'Secundária ',
			'Nativa',
			'',			     
			'Bahia (BA), Paraíba (PB), Pernambuco (PE), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',								 
			'Cerrado, Mata Atlântica',
			'julho a agosto',
			'setembro a outubro',
			'Monóica',
			'Entomofilia',
			'Síliqua',
			'Anemocoria',
			'Folha composta',
			'Oposta',
			'descricao',
			'Espécie muito usada na arborização urbana, devido à beleza de suas flores. Sua madeira é utilizada para construção civil em obras expostas ou externas, cabos de ferramentas, carpintaria, marcenaria, dormentes, esquadrias, forros e vigas. Espécie indicada para a restauração de ecossistemas degradados.');

-- Ipê-branco

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Ipê-branco',
			'QR-Ipê-branco',
			'4',
			'BIGNONIACEAE',
			'Tabebuia roseoalba',
			'(Ridl.) Sandwith',
			'Tabebuia roseoalba (Ridl.) Sandwith',
			'Ipê-branco',
			'Secundária ',
			'Nativa',
			'',
			'Distrito Federal (DF), Goiás (GO), Mato Grosso do Sul (MS), Mato Grosso (MT), Alagoas (AL), Bahia (BA), Ceará (CE), Maranhão (MA), Pernambuco (PE), Piauí (PI), Rio Grande do Norte (RN), Sergipe (SE), Pará (PA), Tocantins (TO), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ) e São Paulo (SP)', 			     
			'Caatinga, Cerrado, Mata Atlântica',
			'agosto a setembro',
			'outubro a novembro',
			'Monóica',
			'Entomofilia',
			'Síliqua',
			'Anemocoria',
			'Folha composta',
			'Oposta',
			'descricao',
			'Espécie muito usada na arborização urbana, devido á beleza de suas flores. Sua madeira é utilizada para construção civil. Espécie indicada para a restauração de ecossistemas degradados.');
			

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Ipê-rosa',
			'QR-Ipê-rosa',
			'4',
			'BIGNONIACEAE',
			'Handroanthus impetiginosus',
			'(Mart. ex DC.) Mattos',
			'Handroanthus impetiginosus (Mart. ex DC.) Mattos',
			'Ipê-rosa',
			'Secundária ',
			'Nativa',
			'',
			'Distrito Federal (DF), Goiás (GO), Mato Grosso do Sul (MS), Mato Grosso (MT), Alagoas(AL), Bahia(BA), Ceará(CE), Maranhão(MA), Pará (PA), Pernambuco(PE), Piauí(PI), Rio Grande do Norte (RN), Sergipe (SE), Acre (AC), Pará (PA), Rondônia (RO), Tocantins (TO), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ) e São Paulo (SP)', 			     
			'Amazônia, Caatinga, Cerrado, Mata Atlântica, Pantanal',
			'julho a agosto',
			'setembro a outubro',
			'Monóica',
			'Entomofilia',
			'Síliqua',
			'Anemocoria',
			'Folha composta',
			'Oposta',
			'descricao',
			'Espécie muito utilizada na arborização urbana devido à beleza de suas flores. Sua madeira é utilizada para construção civil, postes e dormentes. Espécie indicada para a restauração de ecossistemas degradados.');



INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Sequóia',
			'QR-Sequóia',
			'4',
			'CUPRESSACEAE',
			'Sequoia sempervirens',
			'(D.Don.) Endl.',
			'Sequoia sempervirens (D.Don.) Endl.',
			'Sequóia',
			'-',
			'Exótica',
			'América do Norte',
			'',
			'Floresta Temperada',
			'novembro a março',
			'setembro a dezembro',
			'Monóica',
			'Anemofilia',
			'As sementes estão reunidas no estróbilo feminino',
			'Autocoria',
			'Folha simples',
			'Alterna',
			'descricao',
			'Espécie utilizada na indústria madeireira.');
			

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Branquilho',
			'QR-Branquilho',
			'4',
			'EUPHORBIACEAE',
			'Gymnanthes klotzschiana',
			'Müll.Arg.',
			'Gymnanthes klotzschiana Müll.Arg.',
			'Branquilho',
			'Secundária',
			'Nativa',
			'',
			'Mato Grosso do Sul (MS) e Mato Grosso (MT), Alagoas (AL), Bahia (BA), Ceará (CE), Paraíba (PB), Pernambuco (PE), Sergipe (SE), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)', 			   
			'Caatinga, Mata Atlântica',
			'agosto a fevereiro',
			'dezembro a janeiro',
			'Monóica',
			'Entomofilia',
			'Cápsula',
			'Autocoria e Zoocoria',
			'Folha simples',
			'Alterna',
			'descricao',
			'Sua madeira é usada para lenha e carvão. As raízes tem propriedades terapêuticas e são usadas na medicina popular. Espécie indicada para a restauração de ecossistemas degradados.');
			

-- Capixingui

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Capixingui',
			'QR-Capixingui',
			'4',
			'EUPHORBIACEAE',
			'Croton floribundus',
			'Spreng.',
			'Croton floribundus Spreng.',
			'Capixingui',
			'Pioneira',
			'Nativa',
			'',
			'Distrito Federal (DF), Mato Grosso do Sul (MS), Mato Grosso (MT), Alagoas (AL), Bahia (BA), Ceará (CE), Paraíba (PB), Pernambuco (PE), Tocantins (TO), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP) e Paraná (PR)', 			     
			'Mata Atlântica',
			'outubro a dezembro',
			'fevereiro a março',
			'Monóica',
			'Entomofilia',
			'Cápsula esquizocarpo',
			'Autocoria e Zoocoria',
			'Folha simples',
			'Alterna',
			'descricao',
			'Sua madeira é utilizada para caixotaria leve. Por ser uma espécie tipicamente pioneira, o capixingui pode ser utilizado na colonização de áreas degradadas, oferecendo rápido recobrimento do solo.');
			
			
-- Tipuana

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Tipuana',
			'QR-Tipuana',
			'4',
			'FABACEAE',
			'Tipuana tipu',
			'(Benth.) Kuntze',
			'Tipuana tipu (Benth.) Kuntze',
			'Tipuana',
			'-',
			'Exótica',
			'Bolívia e norte da Argentina',
			'',                         
			'Chaco Argentino',
			'novembro a dezembro',
			'dezembro a setembro',
			'Monóica',
			'Entomofilia',
			'Sâmara',
			'Anemocoria',
			'Folha composta',
			'Alterna',
			'descricao',
			'Espécie muito frequente em parques e na arborização urbana, de efeito ornamental notável durante o florescimento. Sua madeira é muito utilizada na construção civil.');

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Angico-gurucaia',
			'QR-angico',
			'4',
			'FABACEAE',
			'Parapiptadenia rigida',
			'(Benth.) Brenan',
			'Parapiptadenia rigida (Benth.) Brenan',
			'Angico-gurucaia',
			'Pioneira à Secundária',
			'Nativa',
			'',				 
			'São Paulo (SP), Paraná (PR), Rio Grande Do Sul (RS) e Santa Catarina (SC)',				   	 
			'Mata Atlântica',
			'outubro a dezembro',
			'março a setembro',
			'Monóica',
			'Melitofilia',
			'Legume',
			'Autocoria e Anemocoria',
			'Folha composta',
			'Alterna',
			'descricao',
			'Espécie muito utilizada na arborização urbana. Sua madeira é usada na construção rural e civil. Espécie indicada para a restauração de florestas ciliares.');


INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Falso-barbatimão',
			'QR-Falso-barbatimão',
			'4',
			'FABACEAE',
			'Cassia leptophylla',
			'Vogel',
			'Cassia leptophylla Vogel',
			'Falso-barbatimão',
			'Secundária',
			'Nativa',
			'',
			'Distrito Federal (DF) e Mato Grosso (MT), Bahia (BA), Pará (PA), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)', 			    				
			'Mata Atlântica',
			'novembro a dezembro',
			'janeiro a maio',
			'Monóica',
			'Entomofilia',
			'Legume',
			'Autocoria',
			'Folha composta',
			'Alterna',
			'descricao',
			'Árvore com flores amarelas, muito uttilizada na arborização urbana. Sua madeira é usada em obras internas e externas, caixotaria e confecções de brinquedos. Espécie indicada para a restauração de ecossistemas degradados.');


INSERT INTO plantas2 (qrcode,
				   	 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Pau-ferro',
			'QR-Pau-ferro',
			'4',
			'FABACEAE',
			'Libidibia ferrea',
			'(Mart. ex Tul.) L.P.Queiroz',
			'Libidibia ferrea (Mart. ex Tul.) L.P.Queiroz',
			'Pau-ferro',
			'Secundária',
			'Nativa',
			'',			    
			'Alagoas (AL), Bahia (BA), Ceará (CE), Maranhão (MA), Paraíba (PB), Pernambuco (PE), Piauí (PI), Rio Grande do Norte (RN), Sergipe (SE), Espírito Santo (ES), Minas Gerais (MG) e Rio de Janeiro (RJ)',								 			                        
			'Caatinga, Cerrado, Mata Atlântica',
			'janeiro a março',
			'julho a setembro',
			'Monóica',
			'Entomofilia',
			'Legume carnoso',
			'Autocoria e Zoocoria',
			'Folha composta',
			'Alterna',
			'descricao',
			'Espécie utilizada na arborização urbana devido à beleza de seu porte. Sua madeira é usada para construção civil e fabricação de móveis. Espécie indicada para a restauração de ecossistemas degradados.');

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Sibipiruna',
			'QR-Sibipiruna',
			'4',
			'FABACEAE',
			'Poincianella pluviosa',
			'(DC.) L.P.Queiroz',
			'Poincianella pluviosa (DC.) L.P.Queiroz',
			'Sibipiruna',
			'Secundária',
			'Nativa',
			'',
			'Mato Grosso do Sul (MS), Mato Grosso (MT), Bahia (BA), Paraíba (PB), Pernambuco (PE), Pará (PA), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ) e Paraná (PR)', 			     				 				 
			'Amazônia, Caatinga Cerrado, Mata Atlântica, Pantanal',
			'setembro a outubro',
			'dezembro a janeiro',
			'Monóica',
			'Entomofilia',
			'Legume',
			'Autocoria',
			'Folha composta',
			'Alterna',
			'descricao',
			'Uma das árvores nativas mais utilizada na ornamentação urbana. Sua madeira é usada para construção civil, marcenaria e carpintaria.');

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
				     familia,
					 binomio,
					 autores,
					 nome_cientifico,
					 nome_popular,
					 grupo_ecologico,
					 origem,
					 centro_origem,
					 ocorrencia,
					 bioma, floracao,
					 frutificacao,
					 sexo,
					 s_polinizacao,
					 tipo_fruto,
					 s_dispersao,
					 tipo_folha,
					 filotaxia,
					 descricao,
					 utilizacoes) 
    VALUES ('QR-Ingá-ferradura',
			'QR-Ingá-ferradura',
			'4',
			'FABACEAE',
			'Inga sessilis',
			'(Vell.) Mart.',
			'Inga sessilis (Vell.) Mart.',
			'Ingá-ferradura',
			'Secundária',
			'Nativa',
			'',		    
			'Bahia (BA), Pará (PA), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',					 
			'Amazônia, Cerrado, Mata Atlântica',
			'agosto a setembro',
			'setembro a outubro',
			'Monóica',
			'Zoofilia e Entomofilia',
			'Legume carnoso',
			'Zoocoria',
			'Folha composta',
			'Alterna',
			'descricao',
			'Espécie indicada para a arborização de jardins e rodovias. Sua madeira é usada em obras internas, esquadrias, forros, móveis, tabuados e palitos de fósforos. Espécie indicada para a restauração de ecossistemas degradados.');
			
			

 INSERT INTO plantas2 (qrcode,
			  		 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Jacarandá',
			'QR-Jacaranda',
			'4',
 			'BIGNONIACEAE',
			'Jacaranda mimosifolia',
			'D. Don',
 			'Jacaranda mimosifolia D. Don',
 			'Jacarandá',
 			'-',
 			'Exótica',
 			'Argentina, Bolívia, Paraguai',
 			'',
 			'Chaco Argentino',
 			'agosto a novembro',
 			'maio a setembro',
 			'Monóica',
 			'Melitofilia',
 			'Cápsula',
 			'Anemocoria',
 			'Folha composta',
 			'Oposta',
 			'descricao',
			'Espécie muito utilizada na arborização urbana, devido à beleza de suas flores. Produz madeira branca, com potencial para aproveitamento em trabalhos leves, confecção de forros e caixotaria em geral.');
			
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Ingá-Peludo',
			'QR-Inga-Peludo',
			'4',
 			'FABACEAE',
			'Inga vulpina',
			'Mart. ex Benth.',
 			'Inga vulpina Mart. ex Benth.',
 			'Ingá-peludo',
 			'Pioneira',
 			'Nativa',
 			'',
 			'Bahia (BA), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR) e Santa Catarina (SC)',
 			'Cerrado e Mata atlântica',
 			'agosto a fevereiro',
 			'outubro a julho',
 			'Monóica',
 			'Zoofilia e Entomofilia',
 			'Legume carnoso',
 			'Zoocoria',
 			'Folha composta',
 			'Alterna',
 			'descricao',
			'Espécie indicada na arborização de jardins e rodovias e para a restauração de ecossistemas degradados.');

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Manduirana',
			'QR-Manduirana',
			'4',
 			'FABACEAE',
			'Senna macranthera',
			'(DC. ex Collad.) H.S.Irwin & Barneby',
 			'Senna macranthera (DC. ex Collad.) H.S.Irwin & Barneby',
 			'Manduirana',
 			'Pioneira',
 			'Nativa',
 			'',
 			'Distrito Federal (DF), Goiás (GO) e Mato Grosso (MT), Alagoas (AL), Bahia (BA), Ceará (CE), Paraíba(PB), Pernambuco (PE), Piauí (PI), Rio Grande do Norte (RN), Tocantins (TO), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ) e São Paulo (SP)',
 			'Caatinga, Cerrado e Mata Atlântica',
 			'dezembro a abril',
 			'julho a agosto',
 			'Monóica',
 			'Entomofilia',
 			'Legume',
 			'Autocoria',
 			'Folha composta',
 			'Alterna',
 			'descricao',
			'A árvore é extremamente ornamental quando em flor, podendo ser usada com sucesso no paisagismo em geral. A madeira pode ser empregada para caixotaria leve, confecção de brinquedos, lenha e carvão. Espécie indicada para a restauração de ecossistemas degradados.');
			

INSERT INTO plantas2 (qrcode,
				     qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Pata-de-Vaca',
			'QR-Pata',
			'4',
 			'FABACEAE',
			'Bauhinia variegata',
			'L.',
 			'Bauhinia variegata L.',
 			'Pata-de-vaca',
 			'-',
 			'Exótica',
 			'Índia',
 			'',
 			'Floresta tropical',
 			'dezembro a abril',
 			'abril a maio',
 			'Monóica',
 			'Entomofilia',
 			'Legume',
 			'Autocoria',
 			'Folha composta',
 			'Alterna',
 			'descricao',
			'Espécie ornamental usada na arborização urbana. Recomendada também para parques e jardins.');
			
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Ginkgo',
			'QR-Ginkgo',
			'4',
 			'GINKGOACEAE',
			'Ginkgo biloba',
			'L.',
 			'Ginkgo biloba L.',
 			'Ginkgo',
 			'-',
 			'Exótica',
 			'Norte da China',
 			'',
 			'Floresta Temperada',
 			'março a maio',
 			'setembro a outubro',
 			'Dióica',
 			'Anemofilia',
 			'Semente contendo envoltório carnoso',
 			'Zoocoria',
 			'Folha simples',
 			'Braquiblasto',
 			'descricao',
			'Pode ser utilizada na arborização urbana no sul e regiões de altitude do sudeste do Brasil, dando-se preferência às plantas masculinas em virtude do mal cheiro dos frutos. Suas folhas são muito empregadas com fins medicinais.');
			

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Canela-Sassafras',
			'QR-Canela',
			'4',
 			'LAURACEAE',
			'Ocotea odorifera',
			'(Vell.) Rohwer',
 			'Ocotea odorifera (Vell.) Rohwer',
 			'Canela-sassafras',
 			'Secundária à Climácica',
 			'Nativa',
 			'',
 			'Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',
 			'Cerrado e Mata Atlântica',
 			'dezembro a abril',
 			'junho a setembro',
 			'Monóica',
 			'Melitofilia',
 			'Baga',
 			'Zoocoria',
 			'Folha simples',
 			'Alterna',
 			'descricao',
			'Espécie de alto valor econômico, pois dela se extrai o óleo-de-sassafrás, usado na perfumaria e na medicina. A madeira é usada na construção civil, como vigas, caibros, tacos para assoalhos, móveis, marcenaria, embarcações e produção de laminas faqueadas.');
			
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Canela-preta',
			'QR-Canela-preta',
			'4',
 			'LAURACEAE',
			'Ocotea catharinensis',
			'Mez',
 			'Ocotea catharinensis Mez',
 			'Canela-preta',
 			'Climácica',
 			'Nativa',
 			'',
 			'Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',
 			'Mata Atlântica',
 			'junho a janeiro',
 			'maio a agosto',
 			'Monóica',
 			'Melitofilia',
 			'Baga',
 			'Zoocoria',
 			'Folha simples',
 			'Alterna',
 			'descricao',
			'Fornece ótima madeira, e também é utilizada para a extração de óleo essencial. Espécie indicada para a restauração de ecossistemas degradados.');
			
INSERT INTO plantas2 (qrcode,
				 	 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Canela-de-cheiro',
			'QR-Canela-de-cheiro',
			'4',
 			'LAURACEAE',
			'Cinnamomum verum',
			'J.Presl',
 			'Cinnamomum verum J.Presl',
 			'Canela-de-cheiro',
 			'-',
 			'Exótica',
 			'Sul da Ásia',
 			'',
 			'Floresta tropical',
 			'janeiro',
 			'maio a agosto',
 			'Monóica',
 			'Melitofilia',
 			'Baga',
 			'Zoocoria',
 			'Folha simples',
 			'Alterna',
 			'descricao',
			'A parte interna da casca do tronco e dos ramos, constitui a canela comercial, com vasto uso na perfumaria e na culinária, devido à suas propriedades aromáticas e condimentares. Espécie popularmente utilizada como estimulante, tônica, carminativa e antiespasmódica.');
			
			
			
			
	INSERT INTO plantas2 (qrcode,
			 qrcode2,
			 qtde_imagem,
			 familia,
			 binomio,
			 autores,
			 nome_cientifico,
			 nome_popular,
			 grupo_ecologico,
			 origem,
			 centro_origem,
			 ocorrencia,
			 bioma, 
			 floracao,
			 frutificacao,
			 sexo,
			 s_polinizacao,
			 tipo_fruto,
			 s_dispersao,
			 tipo_folha,
			 filotaxia,
			 descricao,
			 utilizacoes) 
		VALUES ('QR-Açoita-cavalo',
			'QR-Acoita-cavalo',
			'4',
			'MALVACEAE',
			'Luehea divaricata',
			'Mart. & Zucc.',
			'Luehea divaricata Mart. & Zucc.',
			'Açoita-cavalo',
			'Secundária',
			'Nativa',
			'',
			'Distrito Federal (DF), Goiás (GO), Bahia (BA), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Rio Grande do Sul (RS) e Santa Catarina (SC)',
			'Cerrado e Mata Atlântica',
			'dezembro a abril',
			'maio a julho',
			'Monóica',
			'Melitofilia',
			'Cápsula',
			'Anemocoria',
			'Folha simples',
			'Alterna',
			'descricao',
			'Árvore ornamental com flor lilás muito vistosa. Sua madeira é usada para fazer peças torneadas, roda de carroça, esquadrias e cadeiras. ');

INSERT INTO plantas2 (qrcode,
				 	 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Cedro',
			'QR-Cedro',
			'4',
 			'MELIACEAE',
			'Cedrela fissilis',
			'Vell.',
 			'Cedrela fissilis Vell.',
 			'Cedro',
 			'Secundária à climácica',
 			'Nativa',
 			'',
 			'Distrito Federal (DF), Goiás (GO), Mato Grosso do Sul (MS), Mato Grosso (MT), Alagoas (AL), Bahia (BA), Ceará (CE), Maranhão (MA), Paraíba (PB), Piauí (PI), Sergipe (SE), Acre (AC), Amapá (AM), Pará (PA), Rondônia (RO), Tocantins (TO), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',
 			'Amazônia, Cerrado e Mata Atlântica',
 			'setembro a janeiro',
 			'julho a agosto',
 			'Monóica',
 			'Falenofilia e melitofilia',
 			'Cápsula',
 			'Zoocoria',
 			'Folha composta',
 			'Alterna',
 			'descricao',
			'Sua madeira é utilizada na fabricação de móveis, construção civil, venezianas, rodapés, forros e janelas. Também é utilizada para recomposição de florestas e arborização em parques.');
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,	
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Guabiroba',
			'QR-Guabiroba',
			'4',
 			'MYRTACEAE',
			'Campomanesia xanthocarpa',
			'(Mart.) O.Berg',
 			'Campomanesia xanthocarpa (Mart.) O.Berg',
 			'Guabiroba',
 			'Secundária à climácica',
 			'Nativa',
 			'',
 			'Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',
 			'Mata Atlântica',
 			'outubro a novembro',
 			'dezembro a janeiro',
 			'Monóica',
 			'Entomofilia',
 			'Baga',
 			'Zoocoria',
 			'Folha simples',
 			'Oposta',
 			'descricao',
			'Pode ser utilizada na arborização de fazendas, parques e bosques. Também é usada em tabuados em geral e desdobro, produz lenha e carvão de boa qualidade.');
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Cerejeira-do-Rio-Grande',
			'QR-Cerejeira-do-Rio-Grande',
			'4',
 			'MYRTACEAE',
			'Eugenia involucrata',
			'DC.',
 			'Eugenia involucrata DC.',
 			'Cerejeira-do-Rio-Grande',
 			'Secundária',
 			'Nativa',
 			'',
 			'Distrito Federal (DF), Goiás (GO), Mato Grosso do Sul (MS), Bahia (BA), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',
 			'Cerrado e Mata Atlântica',
 			'agosto a setembro',
 			'outubro a novembro',
 			'Monóica',
 			'Melitofilia',
 			'Baga',
 			'Zoocoria',
 			'Folha simples',
 			'Oposta',
 			'descricao',
			'Espécie vistosa, muito utilizada na arborização urbana. É frutífera e os frutos podem ser consumidos ao natural ou na forma de sucos, licores e geléias.Sua madeira geralmente é utilizada para a fabricação de cabos de ferramentas.');
			
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Araçá-goiaba',
			'QR-Araca',
			'4',
 			'MYRTACEAE',
			'Psidium longipetiolatum',
			'D.Legrand',
 			'Psidium longipetiolatum D.Legrand',
 			'Araçá-goiaba',
 			'Secundária',
 			'Nativa',
 			'',
 			'Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',
 			'Mata Atlântica',
 			'novembro a dezembro',
 			'fevereiro a março',
 			'Monóica',
 			'Entomofilia',
 			'Baga',
 			'Zoocoria',
 			'Folha simples',
 			'Oposta',
 			'descricao',
			'Espécie de valor ornamental que fornece frutos comestíveis e muito apreciados, importante como fonte de alimento para a avifauna. A madeira é de boa qualidade para a confecção de cabos de ferramentas.');
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Murta',
			'Murta',
			'4',
 			'MYRTACEAE',
			'Curitiba prismatica',
			'(D.Legrand) Salywon & Landrum',
 			'Curitiba prismatica (D.Legrand) Salywon & Landrum',
 			'Murta',
 			'Secundária',
 			'Nativa',
 			'',
 			'Paraná (PR) e Santa Catarina (SC)',
 			'Mata Atlântica',
 			'dezembro a fevereiro',
 			'janeiro e março',
 			'Monóica',
 			'Entomofilia',
 			'Baga',
 			'Zoocoria',
 			'Folha simples',
 			'Oposta',
 			'descricao',
			'Árvore majestosa com flor branca e folhas brilhosas, indicada para a ornamentação de bosques e jardins. Sua madeira é utilizada na construção civil em obras externas, mourões e para lenha e carvão.');
			
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Jaboticaba',	
			'QR-Jaboticaba',
			'4',
 			'MYRTACEAE',
			'Plinia peruviana',
			'(Poir.) Govaerts',
 			'Plinia peruviana (Poir.) Govaerts',
 			'Jaboticaba',
 			'Secundária',
 			'Nativa',
 			'',
 			'Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',
 			'Mata Atlântica',
 			'agosto',
 			'outubro a dezembro',
 			'Monóica',
 			'Entomofilia',
 			'Baga',
 			'Zoocoria',
 			'Folha simples',
 			'Oposta',
 			'descricao',
			'Espécie amplamente cultivada em pomares, sendo os seus frutos utilizados para a fabricação de geleias, sucos, sorvetes e licores. É indicada também para a recomposição de florestas, contribuindo para a oferta de alimento para a fauna.');
			
			
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Pitanga',
			'QR-Pitanga',
			'4',
 			'MYRTACEAE',
			'Eugenia uniflora',
			'L.',
 			'Eugenia uniflora L.',
 			'Pitanga',
 			'Secundária à climácica',
 			'Nativa',
 			'',
 			'Mato Grosso do Sul (MS), Bahia (BA), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',
 			'Cerrado, Mata Atlântica e Pampa',
 			'julho a setembro',
 			'outubro a novembro',
 			'Monóica',
 			'Entomofilia',
 			'Baga',
 			'Zoocoria',
 			'Folha simples',
 			'Oposta',
 			'descricao',
			'Espécie com frutos comestíveis, muito utilizados para a fabricação de doces e geleias. Indicada para o plantio em reflorestamentos de áreas degradadas.');
			
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Uvaia',
			'QR-Uvaia',
			'4',
 			'MYRTACEAE',
			'Eugenia pyriformis',
			'Cambess.',
 			'Eugenia pyriformis Cambess.',
 			'Uvaia',
 			'Secundária',
 			'Nativa',
 			'',
 			'Goiás (GO), Mato Grosso do Sul (MS), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',
 			'Cerrado e Mata Atlântica',
 			'agosto a outubro',
 			'dezembro a fevereiro',
 			'Monóica',
 			'Melitofilia',
 			'Baga',
 			'Zoocoria',
 			'Folha simples',
 			'Oposta',
 			'descricao',
			'Espécie utilizada para a ornamentação de parques e jardins. É rica em vitamina C, podendo ser usada na fabricação de doces, sorvetes e geleias.');
			
			
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Oliveira',
			'QR-Oliveira',
			'4',
 			'OLEACEAE',
			'Olea europaea',
			'L.',
 			'Olea europaea L.',
 			'Oliveira',
 			'-',
 			'Exótica',
 			'Região Mediterrânea',
 			'',
 			'Vegetação Mediterrânea',
 			'outubro a dezembro',
 			'março a julho',
 			'Monóica',
 			'Anemofilia',
 			'Drupa',
 			'Zoocoria',
 			'Folha simples',
 			'Alterna',
 			'descricao',
			'Espécie de alto valor econômico, pois dela se obtem as azeitonas e o azeite de oliva, usado na alimentação e como combustível. As folhas têm aplicação medicinal, sendo utilizadas para combater a pressão alta. Nas últimas décadas vem sendo cada vez mais usada no paisagismo.');
			

INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Pinus',
			'QR-Pinus',
			'4',
 			'PINACEAE',
			'Pinus pinea',
			'L.',
 			'Pinus pinea L.',
 			'Pinus',
 			'Não há informações',
 			'Exótica',
 			'Predominantemente no Hemisfério Norte',
 			'',
 			'Floresta Mediterrânea',
 			'abril a junho',
 			'outubro',
 			'Monóica',
 			'Anemofilia',
 			'Estróbilo lenhoso',
 			'Autocoria e Zoocoria',
 			'Folha simples',
 			'Alterna',
 			'descricao',
			'As espécies do gênero Pinus produzem madeira de baixa densidade, muito utilizada para caixotaria, indústria de sapatos e lápis. Sua fibra longa também é usada como celulose para a produção de alguns tipos de papéis. Além da madeira, fornecem resinas que são utilizadas como componente da indústria farmacêutica, de conglomerados e de tintas.');
			
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Carvalho-brasileiro',
			'QR-Carvalho-brasileiro',
			'4',
 			'PROTEACEAE',
			'Roupala montana',
			'Aubl.',
 			'Roupala montana Aubl.',
 			'Carvalho-brasileiro',
 			'Secundária à Climácica',
 			'Nativa',
 			'',
 			'Distrito Federal (DF), Goiás (GO), Mato Grosso do Sul (MS), Mato Grosso (MT), Bahia (BA), Ceará (CE), Paraíba (PB) e Piauí (PI), Acre (AC), Amazonas (AM), Amapá (AP), Pará (PA), Rondonia (RO), Roraima (RR), Tocantins (TO), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',
 			'Amazônia, Caatinga, Cerrado e Mata Atlântica',
 			'novembro a fevereiro',
 			'abril a julho',
 			'Monóica',
 			'Entomofilia e Ornitofilia',
 			'Folículo',
 			'Anemocoria',
 			'Folha simples',
 			'Alterna',
 			'descricao',
			'A espécie possui potencial para ser utilizada como ornamental. Sua madeira, de cor amarela e resistente, já foi muito usada na marcenaria, construção civil e naval. Pode ser utilizada para a recomposição da vegetação em matas ciliares, capoeiras e áreas úmidas.');
			
			
			
INSERT INTO plantas2 (qrcode,	
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Pessegueiro-bravo',
			'QR-Pessegueiro-bravo',
			'4',
 			'ROSACEAE',
			'Prunus myrtifolia',
			'(L.) Urb.',
 			'Prunus myrtifolia (L.) Urb.',
 			'Pessegueiro-bravo',
 			'Secundária à Climácica',
 			'Nativa',
 			'',
 			'Distrito Federal (DF), Goiás (GO), Mato Grosso do Sul (MS), Mato Grosso (MT), Bahia (BA), Ceará (CE), Paraíba (PB), Acre (AC), Amazonas (AM), Amapá (AP), Pará (PA), Rondonia (RO), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',
 			'Amazônia, Caatinga, Cerrado e Mata Atlântica',
 			'julho a setembro',
 			'janeiro a março',
 			'Monóica',
 			'Melitofilia',
 			'Drupa',
 			'Zoocoria',
 			'Folha simples',
 			'Alterna',
 			'descricao',
			'A madeira dessa espécie possui várias aplicações, como confecção de artigos de esporte, cabos de ferramentas, móveis, caibros, instrumentos agrícolas e tábuas para assoalho. É uma espécie promissora para a  utilização em reflorestamentos de ecossistemas degradados, pois os frutos, quando maduros, são avidamente procurados e consumidos pela avifauna.');
			
	INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Cerejeira-japonesa',
			'QR-Cerejeira-japonesa',
			'4',
 			'ROSACEAE',
			'Prunus serrulata',
			'Lindl.',
 			'Prunus serrulata Lindl.',
 			'Cerejeira-japonesa',
 			'-',
 			'Exótica',
 			'Japão',
 			'',
 			'Floresta Temperada',
 			'abril a maio',
 			'junho a julho',
 			'Monóica',
 			'Entomofilia',
 			'Drupa',
 			'Zoocoria',
 			'Folha simples',
 			'Alterna',
 			'descricao',
			'Espécie extremamente ornamental, não somente pelo exuberante florescimento, mas também pela folhagem. É ótima para o paisagismo em geral.');
			
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Chorão',
			'QR-Chorão',
			'6',
 			'SALICACEAE',
			'Salix babylonica',
			'L.',
 			'Salix babylonica L.',
 			'Chorão',
 			'-',
 			'Exótica',
 			'China',
 			'',
 			'Floresta Temperada',
 			'fevereiro a março',
 			'março a abril',
 			'Dióica',
 			'Anemofilia',
 			'Cápsula',
 			'Anemocoria',
 			'Folha simples',
 			'Alterna',
 			'descricao',
			'Espécie cultivada como ornamental em jardins, parques, beira de lagos e cursos de água. Sua madeira é de qualidade regular, muito leve e pouco duradoura, podendo ser utilizada na fabricação de canoas e móveis rústicos.');
			
			
INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-Camboatã',
			'QR-Camboata',
			'4',
 			'SAPINDACEAE',
			'Cupania vernalis',
			'Cambess.',
 			'Cupania vernalis Cambess.',
 			'Camboatã',
 			'Secundária',
 			'Nativa',
 			'',
 			'Distrito Federal (DF), Goiás (GO), Bahia (BA), Amazonas (AM), Pará (PA), Espírito Santo (ES), Minas Gerais (MG), Rio de Janeiro (RJ), São Paulo (SP), Paraná (PR), Rio Grande do Sul (RS) e Santa Catarina (SC)',
 			'Amazônia, Caatinga, Cerrado e Mata Atlântica',
 			'maio a junho',
 			'outubro a janeiro',
 			'Monóica',
 			'Entomofilia',
 			'Cápsula',
 			'Zoocoria',
 			'Folha composta',
 			'Alterna',
 			'descricao',
			'Espécie recomendada para a arborização urbana. Sua madeira é utilizada em construções internas, confecção de varas leves e na marcenaria. As sementes são usadas em artesanatos por algumas comunidades indígenas. A espécie também é indicada para a recomposição de florestas ciliares.');



INSERT INTO plantas2 (qrcode,
					 qrcode2,
					 qtde_imagem,
 				     familia,
					 binomio,
					 autores,
 					 nome_cientifico,
 					 nome_popular,
 					 grupo_ecologico,
 					 origem,
 					 centro_origem,
					 ocorrencia,
 					 bioma, 
					 floracao,
 					 frutificacao,
 					 sexo,
 					 s_polinizacao,
 					 tipo_fruto,
 					 s_dispersao,
 					 tipo_folha,
 					 filotaxia,
 					 descricao,
					 utilizacoes) 
     VALUES ('QR-teste',
			'QR-teste',
			'4',
 			'SALICACEAE',
			'Salix babylonica',
			'L.',
 			'Salix babylonica L.',
 			'Chorão',
 			'Pioneira',
 			'Exótica',
 			'China',
 			'',
 			'Clima Temperado',
 			'fevereiro a março',
 			'março a abril',
 			'Dióica',
 			'Anemofilia',
 			'Cápsula',
 			'Anemocoria',
 			'Folha simples',
 			'Alterna',
 			'descricao',
			'Espécie cultivada como ornamental em jardins, parques, beira de lagos e cursos de água. Sua madeira é de qualidade regular, muito leve e pouco duradoura, podendo ser utilizada na fabricação de canoas e móveis rústicos.');
			
